### ISSUE TITLE
1.13 not working

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/PrettySimpleShop#1]
Heya!
I Really like ur plugin, but it gives me a bunch of errors in 1.13..
i Hope u can fix it

- Pepijn

**Comment by RoboMWM** [comment]
Please paste said errors

**Comment by RoboMWM** [comment]
It only gave me one error, btw. Fixed in https://github.com/MLG-Fortress/PrettySimpleShop/commit/0b5326035916bf2d9d9b7f177bf4b1eebcfd99e1
