### ISSUE TITLE
Dupe glitch w/ enchanted pickaxes

### ISSUE THREAD

**Issue by quarterwave0** [MLG-Fortress/PrettySimpleShop#11]
Hello,
I recently installed Pretty Simple shop on my "Paper" 1.13.2 Minecraft server (versioning info below)
![4b1a3a785a8c88cb8817a602a10d5cf1](https://user-images.githubusercontent.com/47278679/57960858-31305c00-78d9-11e9-9b02-3afcdca62502.png)
With version 1.4.2 of PrettySimpleShop
![288171fb7fa5582101f940408c2dea88](https://user-images.githubusercontent.com/47278679/57960896-6ccb2600-78d9-11e9-8c70-040cfae033b9.png)

**Steps to reproduce:**
Make a shop with an enchanted pickaxe
Open the chest shop's inventory
Have another player buy the pickaxe
Remove the pickaxe from the chest's inventory

**Expected Results:**
The pickaxe is immediately removed from the chest

**Actual results:**
The pickaxe remains in the chest while the player is in the chest inventory, allowing for the player to take the item from the chest, creating a copy.

**Comment by RoboMWM** [comment]
Huh... are you sure this isn't a clientside ghost copy? Does the pickaxe that was taken from the chest work and etc.?

**Comment by RoboMWM** [comment]
Also, it seems the issue has nothing to do with enchanted pickaxes...? Or are you saying this can't be reproduced with other types of items?

**Comment by quarterwave0** [comment]
1. Absolutely sure this is not a ghost copy. The pickaxe can be used, dropped, picked up again, can be safely stored in a chest, etc.

2. Surprisingly enough, it does have to do with that. I tried it with every tool. Bizarrely enough, Enchanted pickaxes, no matter the material, were the only ones vulnerable. To discover that, I spawned in a wooden pickaxe, and gave it an arbitrary enchantment, then sold it. I tried it with every type of pickaxe/tool, and sure enough, only enchanted pickaxes. It's important to note that these pickaxes had 100% durability, I'm not sure if it works with a used pickaxe. (I also tried it with armor and enchanted items)
If you would like me to make a short video clip depicting the bug, I can if you wish.

**Comment by RoboMWM** [comment]
And just to verify, this happens with no other plugins installed?

**Comment by quarterwave0** [comment]
I did not test that, it didn't come to mind. I'm not entirely sure, I will see if I can get another person to test that with. I don't have any plugins installed that directly interact with chests, the receiving of items, or anything that I could imagine to be even tangentially related to such an issue. If you'd like a list, let me know. In the meantime, I'll see if I can convince someone to come on a server with only one plugin.

**Comment by RoboMWM** [comment]
Someone else reported a duplication issue that only occurred when combined with another plugin (for another plugin), so perhaps a similar issue might be present here since this also involves the inventory.

**Comment by quarterwave0** [comment]
Alright, I just tested it with minimal plugins:
`Craftconomy 3-3.3.1`
`PrettySimpleShop`
`Vault`
The issue still occurs. Another player and I could successfully duplicate enchanted pickaxes.
How strange.
Edit: Same server version as the original report, plain default config except for the port in server.properties

**Comment by RoboMWM** [comment]
Is the container a doublechest?

**Comment by RoboMWM** [comment]
I'm going to guess that there's something wrong in the server if it only happens with enchanted pickaxes... I'm calling `Inventory#removeItem` on the container before generating the trade collection window. Especially if it isn't occurring with anything else...

I'm not really sure how to fix this other than doing a special case for enchanted pickaxes I guess. And even then, I'm not really sure how to cleanly go about preventing them from being duplicated.

**Comment by RoboMWM** [comment]
In the meantime, you can try seeing if it still occurs on 1.14 with the 1.5 release

**Comment by quarterwave0** [comment]
Were you able to replicate the issue on your end?
I did not test the bug with double chests, but I will see if I can get someone to test that with.

**Comment by RoboMWM** [comment]
No, just wanted to ensure doublechests weren't the issue.

No, I haven't been able to get anyone else on to try.

**Comment by RoboMWM** [comment]
Is this still an issue with 1.14? Curious to know if this was a bukkit/spigot issue that was resolved or not.

**Comment by RoboMWM** [comment]
So another player has to buy the pickaxe? Shops don't store owner information. Not able to reproduce when I buy the pickaxe.

**Comment by quarterwave0** [comment]
I no longer run a server, so I can't test again, but this bug still occurred right up until I terminated the server. I'm sorry I can't help you further, I've moved onto other things.
> Steps to reproduce:
> Make a shop with an enchanted pickaxe
> Open the chest shop's inventory
> Have **_another player_** buy the pickaxe
> Remove the pickaxe from the chest's inventory

**Comment by RoboMWM** [comment]
Shops don't store owner info so idk why another player has to buy it.

**Comment by Keks4Gaming** [comment]
I tried to reproduce the issue but i cant get it to work. Not in 1.13.2 or 1.14.4 even not in 1.15.1 with TNE as a currency mod.

At the point a character clicks in the book on confirm they dissapear out of the chest.

I have a root Server and can try thing for you if you want.
