### ISSUE TITLE
Plugin Says it is disabled but according to my system it is active?

### ISSUE THREAD

**Issue by HawkI64** [MLG-Fortress/PrettySimpleShop#13]
So im starting a server in minecraft and i have never done this so im very new. I installed the plugin and i hope to use it with Mcmoney which is linked with vault. Not sure what is happening but would love some help with this! :D

![Server 1](https://user-images.githubusercontent.com/51289251/58760847-bfb30780-8580-11e9-989d-17aec6b0525a.PNG)
![server 2](https://user-images.githubusercontent.com/51289251/58760848-bfb30780-8580-11e9-9042-247e80bd1a04.PNG)
![server 3](https://user-images.githubusercontent.com/51289251/58760849-bfb30780-8580-11e9-86a0-a9247ffd323f.PNG)

**Comment by RoboMWM** [comment]
Panels can lie (I.e. are ignorant). Check further up in server log to see why it was disabled.
