### ISSUE TITLE
1.13.1 - Breaking shop, custom chest-name, etc

### ISSUE THREAD

**Issue by BiGUNMAN** [MLG-Fortress/PrettySimpleShop#2]
Config: https://pastebin.com/raw/dXc5KfLX

There's a few 1.13 issues:

1. When you first place down a chest, set a price, and then open the chest: https://i.imgur.com/bLjRZfz.png

2. When you right-click a chest in attempt to buy something from it: https://i.imgur.com/sXZlCPz.png

3. When breaking a shop, the item continues to float until server restart: https://i.imgur.com/ig6Obd4.png

4. When I decided to customize the shop name like so: https://i.imgur.com/PFQVnlf.png - items stopped floating above the shop when I created them. Only when I reset them back to default did the items appear at the top.

Note: I think when I had shops created this way, they weren't really stored in the "chunks_containingShops.data" (because the file wasn't created).

**Comment by RoboMWM** [comment]
Hmm, does it work if you remove the color code in the `priceApplied` key for the first issue?

**Comment by RoboMWM** [comment]
for the first issue.

**Comment by BiGUNMAN** [comment]
No, the error appears regardless of the color code in the priceApplied key: https://i.imgur.com/jNYdx49.png

**Comment by RoboMWM** [comment]
This is weird, as if this were an issue with the String#replaceAll method...

**Comment by RoboMWM** [comment]
uh, can you give me the output of `java -version` because it seems to be working just fine on my server...

**Comment by RoboMWM** [comment]
Ohhhhhh I know why, it's because you're using the standard `$` as your currency symbol. I don't use that on my server lol. And regex is interpreting that instead of accepting it as a literal string.

**Comment by BiGUNMAN** [comment]
@RoboMWM That was all because of the color code in message? And I'd really appreciate it if you could compile the new jar, I don't have the tools to do so..

**Comment by RoboMWM** [comment]
No, color code had nothing to do with it. Will release soon, I added a new feature without a config option.

**Comment by BiGUNMAN** [comment]
What is that new feature?

**Comment by RoboMWM** [comment]
Making a shop without the chest having to be named `shop` or similar. I'll try to release this weekend, been bogged down with other stuff.

**Comment by RoboMWM** [comment]
Whenever it gets approved, https://dev.bukkit.org/projects/prettysimpleshop/files/2625586
