### ISSUE TITLE
PrettySimpleShop spits an error when my players buy an item from other players. 

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/PrettySimpleShop#20]
Hi,

I am currently having a issue with PSS (1.6.0, Paper 1.14.4 build 163, Economy is Vault Based)
When a player purchases an item from a shop, he gets the item and the payment doesn't go to the shop owner. I would like the player to actually get the payment in his inventory (Item Economy), and if inv is full in the shop chest.

Error pastebin: **https://paste.helpch.at/efupazewoh.rb**

Hopefully you can resolve this A.S.A.P.

~ Pepijn

**Comment by RoboMWM** [comment]
Looks like a problem with your economy plugin, not PrettySimpleShop.
