### ISSUE TITLE
Pay with Diamonds

### ISSUE THREAD

**Issue by blenditbeautiful** [MLG-Fortress/PrettySimpleShop#21]
Any chance you would add the ability to pay with diamonds, gold ingots or any other in game item of our choice, similar to the trade sign in EssentialsX? Looking for a more vanilla experience.

**Comment by RoboMWM** [comment]
There are vualt-compatible plugins that use MC items like gringotts. I think those would work?

**Comment by blenditbeautiful** [comment]
That's true. I was thinking more along the lines of you place whatever you want to be paid in the first slot of the chest and then what the buyer receives in the second slot. (i.e. 1 diamond, 64 firework_rockets) and the diamonds would end up in the chest as opposed to a Gringotts vault (i.e. what they do on Hermitcraft). I understand if that's outside the scope of what you had in mind for this plugin though.

**Comment by RoboMWM** [comment]
Yea, definitely would require a significant overhaul, as the plugin is designed to sell a singular item type from a chest without any need to specify what that item is.

Idk if I'll look into making a barter system. But if I were to, that'd be much closer to what you're looking for.

**Comment by blenditbeautiful** [comment]
Okay, no worries!
