### ISSUE TITLE
another setprice issue

### ISSUE THREAD

**Issue by Ciscover1** [MLG-Fortress/PrettySimpleShop#36]
I installed the plugin, placed a chest and put /setprice 10, they says "Open the shop to apply your shiny new price.." and not work.

I not speak very good the english xd sorry.

**Comment by Ciscover1** [comment]
https://pastebin.com/JvdfpgEe

**Comment by RoboMWM** [comment]
Please actually restart your server. I'm guessing something else is going on, and that log isn't very helpful since something else is going on apparently.

**Comment by RoboMWM** [comment]
Have you restarted your server yet?

**Comment by DiepAnDot** [comment]
i used it and now it doesnt work its disablede due to no economy plugin

**Comment by DiepAnDot** [comment]
> i used it and now it doesnt work its disablede due to no economy plugin


this is what it says on console [00:21:40] [Server thread/INFO]: [PrettySimpleShop] Enabling PrettySimpleShop v1.7.2-0a3625e
[00:21:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:21:40] [Server thread/INFO]: Done (8.154s)! For help, type "help"
[00:21:40] [Server thread/ERROR]: [PrettySimpleShop] No economy plugin was found. Disabling.
[00:21:40] [Server thread/INFO]: [PrettySimpleShop] Disabling PrettySimpleShop v1.7.2-0a3625e

**Comment by plasticsucks** [comment]
hi I just added the plugin! I tried using the /setprice command but it said "an internal error occurred while attempting to perform this command" can anyone help?? not sure what I'm doing wrong!

**Comment by RoboMWM** [comment]
check the console, an error is printed there. Also, please open a new issue instead of hijacking this one as this is not the same issue (this guy has no error message).

**Comment by plasticsucks** [comment]
sorry! I just saw doesn't work and posted here! my bad!

**Comment by RoboMWM** [comment]
Closing this since @Ciscover1 has yet to respond...
