### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by deralmas** [MLG-Fortress/PrettySimpleShop#54]
I just noticed that there's no licence. You should add one otherwise all rights go to you by default.

**Comment by RoboMWM** [comment]
Yea, I still haven't decided on a license yet.

I'm still not really sure what I want to do, I know I've asked before but yea.

If I remember my concerns, it had something to do with not wanting/wanting to understand how GPL license can infect others, and preventing others from just flat out copying code.

I think 4 clause BSD/old BSD license was one I was looking at but idk at this point. Could do MIT, or just normal BSD 3 clause... 

But yea that's basically the answer, I still haven't decided and given the "I'm not a lawyer" landscape it's kinda hard to find good resources to learn anything beyond simplistic basics.

**Comment by deralmas** [comment]
@RoboMWM don't worry, take your time. Have you consulted https://choosealicense.com/ and https://tldrlegal.com/? Those might be useful resources if you didn't know them already.

**Comment by RoboMWM** [comment]
I have, kind of what I referred to as "simplistic basics" lol

**Comment by RoboMWM** [comment]
done https://github.com/MLG-Fortress/PrettySimpleShop/commit/2d258e63e001f118ad62e5b18ba507ae3a554fec

**Comment by RoboMWM** [comment]
at this rate I despise react and electron and would rather have ppl copy my code than being forced to load laggy heavy web tech lul
