### ISSUE TITLE
Holograms Won't Go Away

### ISSUE THREAD

**Issue by Andarius68** [MLG-Fortress/PrettySimpleShop#59]
After removing chests of a player who is no longer allowed on my server I still have the holograms from their shop chests. I tried the command for removing invisible armor stands but it said no entity was found. How can I delete these leftover holograms from the chests that are no longer there?

Nevermind. I figured it out. I should have just not included an entity type and gone with kill all entities within 5 blocks. That worked. Also, I think I was using essentials kill command instead of vanilla minecraft command.

**Comment by RoboMWM** [comment]
the dropped item is the one showing the text. There are no armor stands spawned by this plugin.

I'm assuming you deleted the chests through a non-conventional method (worldedit I presume)?

**Comment by Andarius68** [comment]
Core Protect rollback actually.

**Comment by RoboMWM** [comment]
Ah ok thanks.
Yea, PrettySimpleShop won't know that the shop is gone until it's reloaded or next restart since it has no way of knowing the block was removed.

**Comment by Andarius68** [comment]
That makes sense and ya know, sense you mentioned it, it never even occured
to me to try reloading the plugin while I was thinking of ways to make them
go away. Doh! Lol.
