### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by RioArdsy** [MLG-Fortress/PrettySimpleShop#8]
Help. Invalid plugin.yml

ERROR Log:
https://pastebin.com/rQ3AWJti

**Comment by RoboMWM** [comment]
Hmm, try redownloading the plugin?

**Comment by RoboMWM** [comment]
Yea, try redownloading the plugin. 1.4.2 is working fine for me. Guessing your download corrupted or something.
