### ISSUE TITLE
problem with shop

### ISSUE THREAD

**Issue by tatezi** [MLG-Fortress/PrettySimpleShop#9]
when i did /setprice its output was the description of the command "/setprice (price)- sets the price per item per shop..." inculded is /version and /version prettysimpleshop. i am using 1.13.2 if that helps
<img width="1082" alt="screen shot 2019-03-05 at 8 12 46 pm" src="https://user-images.githubusercontent.com/48268793/53853770-0abe7e00-3f84-11e9-8dc4-3608e303b494.png">
<img width="518" alt="screen shot 2019-03-05 at 8 13 04 pm" src="https://user-images.githubusercontent.com/48268793/53853771-0d20d800-3f84-11e9-8e02-42c0a3d84704.png">

**Comment by RoboMWM** [comment]
Did you put in the price as the parameter? E.g. `/setprice 20`

**Comment by RoboMWM** [comment]
I'm going to guess that was the case.
